名称：构建 mpv-android so

在:
  推:
  拉取请求:
  工作流触发:

工作:
  构建:
    运行于：ubuntu-22.04
    步骤:
      - 名称: 结账代码
        使用：actions/checkout@v4
        与：
          子模块：递归

      - 名称: 设置Java
        使用：actions/setup-java@v4
        与：
          java版本：'17'
          分布：temurin

      - 名称: 安装依赖项
        运行： |
          执行apt-get更新
          sudo apt-get install -y python3 python3-pip python3-setuptools python3-wheel \
            build-essential pkg-config libtool autoconf automake cmake \
            unzip wget curl yasm nasm ninja-build

      - 名称: 下载 Android NDK
        运行： |
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
          unzip -q android-ndk-r23b-linux.zip -d $HOME
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-r23b" >> $GITHUB_ENV

      - 名称： 构建 mpv-android so
        运行： |
          cd buildscripts
          ./buildall.sh arm64-v8a

      - 名称： 上传软件工件
        使用：actions/upload-artifact@v4
        与：
          name：mpv-android-so-arm64-v8a
          路径：app/src/main/libs/arm64-v8a/*.so
