name: Build mpv-android so

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-setuptools python3-wheel \
            build-essential pkg-config libtool autoconf automake cmake \
            unzip wget curl yasm nasm ninja-build

      - name: Download SDK and dependencies
        run: |
          cd buildscripts
          ./download.sh

      - name: Build mpv-android so
        run: |
          cd buildscripts
          ./buildall.sh --arch arm64 mpv-android

      - name: Upload so artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mpv-android-so-arm64-v8a
          path: app/src/main/libs/arm64-v8a/*.so 
