名称：构建 mpv-android so

在请将以下网页文本翻译成中文，只输出翻译结果，不输出任何其他解释，若文本已经是中文了，则直接用中文复述一遍。翻译结果保持格式不变。输入：:
  工作流触发:

工作：
  构建:
    运行于：ubuntu-latest
    步骤：
      - 名称：结账代码
        使用：actions/checkout@v3
        与：
          子模块：递归

      - 名称: 安装依赖项
        运行： |
          请将以下文本翻译成简体中文：           sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-setuptools python3-wheel \
            构建基本包 pkg-config libtool autoconf automake cmake
            解压wget curl yasm nasm ninja-build

      - 名称: 下载 Android NDK
        运行： |
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
          unzip -q android-ndk-r23b-linux.zip -d $HOME
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-r23b" >> $GITHUB_ENV

      - 名称： 构建 mpv-android so
        运行： |
          cd buildscripts
          ./buildall.sh arm64-v8a

      - 名称：上传软件工件
        使用：actions/upload-artifact@v3
        与：
          名称：mpv-android-so-arm64-v8a
          路径：app/src/main/libs/arm64-v8a/*.so
