name: Build mpv-android so

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-setuptools python3-wheel \
            build-essential pkg-config libtool autoconf automake cmake \
            unzip wget curl yasm nasm ninja-build

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
          unzip -q android-ndk-r23b-linux.zip -d $HOME
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-r23b" >> $GITHUB_ENV

      - name: Build mpv-android so
        run: |
          cd buildscripts
          ./buildall.sh arm64-v8a

      - name: Upload so artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mpv-android-so-arm64-v8a
          path: app/src/main/libs/arm64-v8a/*.so
